### ISSUE TITLE
As long as the client attacks any creature, it will be kicked out of the server

### ISSUE THREAD

**Issue by linxcy** [hamusuke0323/DamageIndicatorForge#1]
the screen shows that  ‘’The received string length is longer than maximum allowed (29 > 20)’

**Comment by linxcy** [comment]
[latest.log](https://github.com/hamusuke0323/DamageIndicatorForge/files/7763950/latest.log)
this is the log
and minecraft versions is 1.12.2

**Comment by hamusuke0323** [comment]
Thanks for reporting, I fixed this bug.
