### ISSUE TITLE
the newest vision of 1.12.2 crash on sending Immune.  

### ISSUE THREAD

**Issue by linxcy** [hamusuke0323/DamageIndicatorForge#3]

**Comment by linxcy** [comment]
[crash-2022-03-06_15.04.01-server.txt](https://github.com/hamusuke0323/DamageIndicatorForge/files/8192124/crash-2022-03-06_15.04.01-server.txt)
this is the crash report

**Comment by hamusuke0323** [comment]
i fixed it. thank you for reporting.
