### ISSUE TITLE
the game crash immediately, while install Not Enough IDs

### ISSUE THREAD

**Issue by KiiroDAYO** [hamusuke0323/DamageIndicatorForge#6]
[crash-2022-06-10_10.19.46-client.txt](https://github.com/hamusuke0323/DamageIndicatorForge/files/8875500/crash-2022-06-10_10.19.46-client.txt)

**Comment by KiiroDAYO** [comment]
The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader

**Comment by hamusuke0323** [comment]
hmm...
have you tried to update Just Enough Items?

**Comment by KiiroDAYO** [comment]
Yes. I have update Just Enough Items to the latest version4.16.1.302.
and it still crashing...
But I have a new solution by add the [Mixin Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) mod to your instance.  and job well done

**Comment by KiiroDAYO** [comment]
Big thanks to the MAtmos

**Comment by hamusuke0323** [comment]
I see. Difference of Mixin version will make Minecraft crash.
But thanks to the mod, we solved this problem. very nice.
